version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Tallinn
    open-pull-requests-limit: 5
    groups:
      java-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Tallinn
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
